import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import '../node_modules/bulma/css/bulma.min.css'
import Nav from '../src/components/nav'
import Footer from '../src/components/footer'
import Header from '../src/components/header'
import Tabs from '../src/components/toggle-tab';
import Cobrinha from '../src/components/cobrinha'

export default function Home() {


  return (
    <div className={"container "+styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />

      <Tabs />
      <br />
      <Cobrinha />

      <Footer className={styles.footer} />
      


      
    </div>
  )
}
