import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import '../node_modules/bulma/css/bulma.min.css'
import Nav from '../src/components/nav'
import Footer from '../src/components/footer'
import Header from '../src/components/header'
import Tabs from '../src/components/toggle-tab';
import Cobrinha from '../src/components/cobrinha';
import Accessibility from '../src/components/accessibility';
import Features from '../src/components/features';
import Customers from '../src/components/customers';

export default function Home() {


  return (
    <div className={"container "+styles.container}>
      <Head>
        <title>My page senai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/2099.ico" />
      </Head>
      <Nav />
      <Header />

      <Tabs />
      <br />
      <Cobrinha />
      <br />
      <Accessibility />
      <br />
      <Cobrinha />
      <br />
      <Features />
      <br />
      <Cobrinha />
      <br />
      <Customers />

      <Footer />
      


      
    </div>
  )
}
